name: PyPI Release Workflow

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Determine if it's a pre-release
        id: check_prerelease
        run: echo "IS_PRERELEASE=${{ github.event.release.prerelease }}" >> $GITHUB_ENV

      - name: Check if it's a tag
        id: check_tag
        run: echo "IS_TAG=${{ startsWith(github.ref, 'refs/tags/') }}" >> $GITHUB_ENV

      - name: Check if it's a full release
        if: ${{ env.IS_TAG == 'true' && env.IS_PRERELEASE != 'true' }}
        run: echo "A full release was found."

      - name: FAKE Publish production distribution to PyPI
        if: |
          env.IS_TAG == 'true' &&
          env.IS_PRERELEASE != 'true'
        run: echo "A fulll release was found (2)"

