name: PyPI Release Workflow

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Tell me the VALUES
        run: |
          echo PRE REL ${{ github.event.release.prerelease }}
          echo EVENT   ${{ github.event_name }}
          echo REL     ${{ github.event_name == 'release' }}
          echo ACTION  ${{ github.event.action}}
          echo PUB     ${{ github.event.action == 'published' }}

      - name: Tell Me If This Is a RELEASE
        if: github.event_name == 'release' && github.event.action == 'published' && ! github.event.release.prerelease
        run: echo "A FULL release was found"

      - name: Tell Me If This Is a PRE-RELEASE
        if: github.event_name == 'release' && github.event.action == 'published' && github.event.release.prerelease
        run: echo "A PRE-release was found"
