name: production

on:
  push:
    branches: [ production, "v[0-9]+.[0-9]+.post" ]
  release:
    types: [ published ]

jobs:
  build-n-publish-to-pypi:
    runs-on: ubuntu-20.04
    concurrency: build-n-publish-to-pypi

    steps:
      - name: Checkout production
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}
          fetch-depth: 0

      - name: Determine if it's a pre-release
        id: check_prerelease
        run: echo "IS_PRERELEASE=${{ github.event.release.prerelease }}" >> $GITHUB_ENV

      - name: Publish production distribution to PyPI
        if: |
          startsWith(github.ref, 'refs/tags') &&
          ${{ env.IS_PRERELEASE != 'true' }}
        run: echo "DOING RELEASE"
#        uses: pypa/gh-action-pypi-publish@v1.4.2
#        with:
#          password: ${{ secrets.PYPI_API_TOKEN }}

