name: PyPI Release Workflow

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: FAKE Publish production distribution to PyPI
        if: "!github.event.release.prerelease"
        run: echo "A fulll release was found (2)"

